[project]
name = "qshare"
version = "0.2.5"
description = "Quickly share local files through a public TryCloudflare tunnel."
readme = "README.md"
authors = [
    { name = "steinvenic", email = "761701732@qq.com" }
]
requires-python = ">=3.6"
dependencies = [
    "qrcode==7.3",
]

[project.scripts]
qshare = "qshare.cli:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
